version: v1

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    env_file:
      ./.env/.django.env
    depends_on:
      - db

  db:
    image: postgres
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env/.postgres.env

volumes:
  db_data:
