# Generated by Django 3.2.4 on 2021-06-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='action',
            field=models.CharField(choices=[('create_product', 'Create a new product'), ('update_product_details', 'Update product details'), ('delete_product', 'Delete a product'), ('add_stock', 'Increment the current stock of a product'), ('remove_stock', 'Decrement the current stock of a product'), ('discount_product', 'Add a discount to a product'), ('remove_discount', 'Remove discount from a product')], max_length=255),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
